# Catchy adjectives for countries to make titles more engaging
COUNTRY_ADJECTIVES = {
    # Major Film-Producing Countries
    "US": ["American", "Hollywood"],
    "GB": ["British", "English"],
    "FR": ["French", "Français", "Parisian"],
    "DE": ["German", "Deutsch", "Berlin"],
    "JP": ["Japanese", "Nippon", "Tokyo"],
    "KR": ["Korean", "K-Drama"],
    "IN": ["Indian", "Bollywood"],
    "CN": ["Chinese", "Mandarin"],
    "ES": ["Spanish", "Español"],
    "IT": ["Italian", "Italiano"],
    "CA": ["Canadian", "Maple Leaf"],
    "AU": ["Australian", "Down Under"],
    "HK": ["Hong Kong", "Cantonese"],
    "TW": ["Taiwanese", "Formosan"],
    "RU": ["Russian", "Soviet"],
    "BR": ["Brazilian", "Samba"],
    "MX": ["Mexican", "Latino"],
    "SE": ["Swedish", "Nordic"],
    "DK": ["Danish", "Nordic"],
    "NO": ["Norwegian", "Nordic"],
    "FI": ["Finnish", "Nordic"],
    "NL": ["Dutch", "Netherlands"],
    "BE": ["Belgian", "Flemish"],
    "PL": ["Polish", "Warsaw"],
    "CZ": ["Czech", "Prague"],
    "GR": ["Greek", "Athenian"],
    "TR": ["Turkish", "Istanbul"],
    "TH": ["Thai", "Bangkok", "Southeast Asian"],
    "PH": ["Filipino"],
    "ID": ["Indonesian", "Southeast Asian"],
    "MY": ["Malaysian", "Southeast Asian"],
    "SG": ["Singaporean", "Lion City", "Southeast Asian"],
    "VN": ["Vietnamese", "Southeast Asian"],
    "AR": ["Argentine", "Tango"],
    "CL": ["Chilean", "Andean"],
    "CO": ["Colombian", "Latin"],
    "PE": ["Peruvian", "Andean"],
    "ZA": ["South African", "African"],
    "EG": ["Egyptian", "Nile"],
    "NG": ["Nigerian", "Nollywood"],
    "IE": ["Irish", "Celtic"],
    "NZ": ["New Zealand", "Kiwi", "Aotearoa"],
    "IS": ["Icelandic", "Nordic"],
    "AT": ["Austrian", "Alpine"],
    "CH": ["Swiss", "Alpine"],
    "PT": ["Portuguese", "Iberian"],
    "RO": ["Romanian", "Eastern European"],
    "HU": ["Hungarian", "Central European"],
    "BG": ["Bulgarian", "Balkan"],
    "RS": ["Serbian", "Balkan"],
    "HR": ["Croatian", "Balkan"],
    "SI": ["Slovenian", "Balkan"],
    "SK": ["Slovak", "Bratislava", "Central European"],
    "IL": ["Israeli", "Middle Eastern"],
    "IR": ["Iranian", "Persian"],
    "SA": ["Saudi", "Arabian"],
    "AE": ["Emirati", "Arabian"],
    "PK": ["Pakistani", "South Asian"],
    "BD": ["Bangladeshi", "South Asian"],
    "LK": ["Sri Lankan", "South Asian"],
    "NP": ["Nepalese", "Nepali"],
    "MM": ["Myanmar", "Burmese"],
    "KH": ["Cambodian", "Southeast Asian"],
    "LA": ["Laotian", "Southeast Asian"],
    # Additional countries with catchy adjectives
    "AD": ["Andorran"],
    "AF": ["Afghan"],
    "AG": ["Antiguan"],
    "AI": ["Anguillan"],
    "AL": ["Albanian"],
    "AM": ["Armenian"],
    "AO": ["Angolan"],
    "AQ": ["Antarctic"],
    "AS": ["Samoan"],
    "AW": ["Aruban"],
    "AZ": ["Azerbaijani"],
    "BA": ["Bosnian"],
    "BB": ["Barbadian"],
    "BF": ["Burkinabé"],
    "BH": ["Bahraini"],
    "BI": ["Burundian"],
    "BJ": ["Beninese"],
    "BM": ["Bermudian"],
    "BN": ["Bruneian"],
    "BO": ["Bolivian"],
    "BS": ["Bahamian"],
    "BT": ["Bhutanese"],
    "BW": ["Botswanan"],
    "BY": ["Belarusian"],
    "BZ": ["Belizean"],
    "CC": ["Cocos Islander"],
    "CD": ["Congolese"],
    "CF": ["Central African"],
    "CG": ["Congolese"],
    "CI": ["Ivorian"],
    "CK": ["Cook Islander"],
    "CM": ["Cameroonian"],
    "CR": ["Costa Rican"],
    "CU": ["Cuban"],
    "CV": ["Cape Verdean"],
    "CY": ["Cypriot"],
    "DJ": ["Djiboutian"],
    "DM": ["Dominican"],
    "DO": ["Dominican"],
    "DZ": ["Algerian"],
    "EC": ["Ecuadorian"],
    "EE": ["Estonian"],
    "EH": ["Sahrawi"],
    "ER": ["Eritrean"],
    "ET": ["Ethiopian"],
    "FJ": ["Fijian"],
    "FK": ["Falkland"],
    "FM": ["Micronesian"],
    "FO": ["Faroese"],
    "GA": ["Gabonese"],
    "GD": ["Grenadian"],
    "GE": ["Georgian"],
    "GF": ["French Guianese"],
    "GH": ["Ghanaian"],
    "GI": ["Gibraltarian"],
    "GL": ["Greenlandic"],
    "GM": ["Gambian"],
    "GN": ["Guinean"],
    "GP": ["Guadeloupean"],
    "GQ": ["Equatorial Guinean"],
    "GS": ["South Georgian"],
    "GT": ["Guatemalan"],
    "GU": ["Guamanian"],
    "GW": ["Guinea-Bissauan"],
    "GY": ["Guyanese"],
    "HM": ["Heard Islander"],
    "HN": ["Honduran"],
    "HT": ["Haitian"],
    "IO": ["British Indian Ocean"],
    "IQ": ["Iraqi"],
    "JM": ["Jamaican"],
    "JO": ["Jordanian"],
    "KE": ["Kenyan"],
    "KG": ["Kyrgyz"],
    "KI": ["Kiribati"],
    "KM": ["Comoran"],
    "KN": ["Kittitian"],
    "KP": ["North Korean"],
    "KW": ["Kuwaiti"],
    "KY": ["Caymanian"],
    "KZ": ["Kazakh"],
    "LB": ["Lebanese"],
    "LC": ["Saint Lucian"],
    "LI": ["Liechtensteiner"],
    "LR": ["Liberian"],
    "LS": ["Basotho"],
    "LT": ["Lithuanian"],
    "LU": ["Luxembourgish"],
    "LV": ["Latvian"],
    "LY": ["Libyan"],
    "MA": ["Moroccan"],
    "MC": ["Monacan"],
    "MD": ["Moldovan"],
    "ME": ["Montenegrin"],
    "MG": ["Malagasy"],
    "MH": ["Marshallese"],
    "MK": ["Macedonian"],
    "ML": ["Malian"],
    "MN": ["Mongolian"],
    "MO": ["Macanese"],
    "MP": ["Northern Mariana"],
    "MQ": ["Martiniquais"],
    "MR": ["Mauritanian"],
    "MS": ["Montserratian"],
    "MT": ["Maltese"],
    "MU": ["Mauritian"],
    "MV": ["Maldivian"],
    "MW": ["Malawian"],
    "MZ": ["Mozambican"],
    "NA": ["Namibian"],
    "NC": ["New Caledonian"],
    "NE": ["Nigerien"],
    "NF": ["Norfolk Islander"],
    "NI": ["Nicaraguan"],
    "OM": ["Omani"],
    "PA": ["Panamanian"],
    "PF": ["French Polynesian"],
    "PG": ["Papua New Guinean"],
    "PM": ["Saint-Pierrais"],
    "PN": ["Pitcairn"],
    "PR": ["Puerto Rican"],
    "PS": ["Palestinian"],
    "PW": ["Palauan"],
    "PY": ["Paraguayan"],
    "QA": ["Qatari"],
    "RE": ["Réunionnais"],
    "RW": ["Rwandan"],
    "SB": ["Solomon Islander"],
    "SC": ["Seychellois"],
    "SD": ["Sudanese"],
    "SH": ["Saint Helenian"],
    "SJ": ["Svalbard"],
    "SL": ["Sierra Leonean"],
    "SM": ["Sammarinese"],
    "SN": ["Senegalese"],
    "SO": ["Somali"],
    "SR": ["Surinamese"],
    "SS": ["South Sudanese"],
    "ST": ["São Toméan"],
    "SV": ["Salvadoran"],
    "SY": ["Syrian"],
    "SZ": ["Swazi"],
    "TC": ["Turks and Caicos"],
    "TD": ["Chadian"],
    "TG": ["Togolese"],
    "TJ": ["Tajik"],
    "TK": ["Tokelauan"],
    "TL": ["Timorese"],
    "TM": ["Turkmen"],
    "TN": ["Tunisian"],
    "TO": ["Tongan"],
    "TT": ["Trinidadian"],
    "TV": ["Tuvaluan"],
    "TZ": ["Tanzanian"],
    "UA": ["Ukrainian"],
    "UG": ["Ugandan"],
    "UM": ["US Outlying"],
    "UY": ["Uruguayan"],
    "UZ": ["Uzbek"],
    "VA": ["Vatican"],
    "VC": ["Saint Vincentian"],
    "VE": ["Venezuelan"],
    "VG": ["British Virgin Islander"],
    "VI": ["US Virgin Islander"],
    "VU": ["Vanuatuan"],
    "WF": ["Wallisian"],
    "WS": ["Samoan"],
    "YE": ["Yemeni"],
    "YT": ["Mahoran"],
    "ZM": ["Zambian"],
    "ZW": ["Zimbabwean"],
}
