services:
  - type: web
    name: yaca-addon
    runtime: node
    plan: free
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_URL
        sync: false
      - key: TRAKT_CLIENT_ID
        sync: false
      - key: TRAKT_CLIENT_SECRET
        sync: false
